name: Leaked Secrets Scan
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v2.0.97
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
